apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-admin
  namespace: default
subjects:
  - kind: User
    name: mfanjie
    apiGroup: rbac.authorization.k8s.io
<<<<<<< HEAD
=======
#  - kind: ServiceAccount
#    name: default
#    namespace: kube-system
>>>>>>> 5ee343253f123e52d3856d241c7218d15d3ef9a6
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io